---
- hosts: win22         # all / none
  gather_facts: false
  vars_files:
    - "vars/common.vars"
  tasks:

    - name: Create Windows User 
      win_user:
        name: "{{ item }}"
        password: "{{ AWA_Password }}"
        state: present
        groups:
            - Users
        update_password: on_create
        password_expired: true
      loop: "{{ AWA_Users }}"
      tags:
        - all

    # - name: Allow log on through Remote Desktop Services
    #   win_user_right:
    #     name: SeDenyRemoteInteractiveLogonRight
    #     users: "{{ item }}"
    #     action: set
    #   loop: "{{ AWA_Users }}"
    #   tags:
    #     - all

    # - name: Install Chocolatey 
    #   win_chocolatey:
    #       name: chocolatey
    #       state: latest
    #   tags:
    #     - all

    # - name: Install .NET Framework 3.5
    #   win_shell: Install-WindowsFeature NET-Framework-Core
    #   tags:
    #     - "3x"
    #     - all

    # .Net Framework 4.8 for Windows Server 2022
    # .Net Framework 4.7 for Windows Server 2019
    # .Net Framework 4.5 for Windows Server 2016 
    # - name: Install .NET Framework 4.8/4.7/4.5
    #   win_chocolatey:
    #     name: "{{ Net_Framework }}"
    #     state: present
    #   tags:
    #     - "4x"
    #     - all

    # - name: Install IIS Web-Server with sub features and management tools
    #   win_feature:
    #     name: Web-Server
    #     state: present
    #     include_sub_features: yes
    #     include_management_tools: yes
    #   tags:
    #     - all

    # - name: Install IIS Web-Server with Specific Features
    #   win_feature:
    #     name: "{{ item }}"
    #     state: present
    #   loop: "{{ IIS_Features }}"  
    #   tags:
    #     - all

    # - name: Reboot Windows Server
    #   win_reboot:
    #   tags:
    #     - all